version: '2'
services:
    gateway-app:
        image: khaledmoalla/gateway:1.0
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:mysql://gateway-mysql:3306/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false'
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - '8080:8080'
    gateway-mysql:
        image: 'mysql:5.7.20'
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=gateway
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    
    microservice1-app:
        image: khaledmoalla/microservice1:1.0
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - JHIPSTER_SLEEP=40
            - JHIPSTER_REGISTRY_PASSWORD=admin
    
    microservice2-app:
        image: khaledmoalla/microservice2:1.0
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - JHIPSTER_SLEEP=50
            - JHIPSTER_REGISTRY_PASSWORD=admin
    
    microservice3-app:
        image: khaledmoalla/microservice3:1.0
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - JHIPSTER_SLEEP=60
            - JHIPSTER_REGISTRY_PASSWORD=admin
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
    logagent:
        image: 'sematext/logagent:latest'
        environment:
            - LOGSENE_TOKEN=345cdfbe-824b-4d00-9f56-7ddaca466960 
            - SPM_RECEIVER_URL=https://spm-receiver.eu.sematext.com
            - LOGSENE_RECEIVER_URL=https://logsene-receiver.eu.sematext.com
            - EVENTS_RECEIVER_URL=https://event-receiver.eu.sematext.com
            - affinity:container!=*sematext-agent*
        cap_add:
            - SYS_ADMIN
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/etc/localtime:/etc/localtime:ro'

    monitoragent:
        image: 'sematext/logagent:latest'
        environment:
            - LOGSENE_TOKEN=345cdfbe-824b-4d00-9f56-7ddaca466960 
            - SPM_TOKEN=eddd236f-xxxxxxxxxxxxxx-83da84b71448
            - SPM_RECEIVER_URL=https://spm-receiver.eu.sematext.com
            - LOGSENE_RECEIVER_URL=https://logsene-receiver.eu.sematext.com
            - EVENTS_RECEIVER_URL=https://event-receiver.eu.sematext.com
            - affinity:container!=*sematext-agent*
        cap_add:
            - SYS_ADMIN
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/:/rootfs:ro'
