version: '2'
services:
    splunkentreprise:
        hostname: splunkenterprise 
        image: splunk/splunk:7.0.3 
        environment:
         SPLUNK_START_ARGS: --accept-license --answer-yes
         SPLUNK_USER: root
        ports:
         - "8000:8000"
         - "8088:8088/tcp"

