#common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Docker

jhipster:
    security:
        authentication:
            jwt:
                base64-secret: NmJiOThlZjkyMWMxYTA5Y2E2MWU0NTViNTRjOWIzZjVlMTY0MTFlMjE0NjBiNzI0ZGY3YTAzZWU4NTZiOWY3YWFmNDI0ZDgyZTRhZjczYWQ5NTVmMDlmODc4NGFhMzIyMTMyZg==

eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
